version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - 3000:3000
    environment:
      - SWITCHBOT_TOKEN=${SWITCHBOT_TOKEN}
